<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'created_at' => '2023-08-04 20:19:55',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-list',
                'id' => 1,
                'is_external' => 0,
                'lft' => 29,
                'link' => '/admin/menu-item',
                'name' => 'Menu',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => 14,
                'rgt' => 30,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            1 => 
            array (
                'created_at' => '2023-08-21 19:40:35',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-cog',
                'id' => 6,
                'is_external' => 0,
                'lft' => 28,
                'link' => NULL,
                'name' => 'Configuraciones',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 43,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            2 => 
            array (
                'created_at' => '2023-08-21 20:27:03',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-home',
                'id' => 22,
                'is_external' => 0,
                'lft' => 2,
                'link' => '/admin/dashboard',
                'name' => 'Panel',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 3,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            3 => 
            array (
                'created_at' => '2023-08-21 20:34:28',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-warehouse',
                'id' => 23,
                'is_external' => 0,
                'lft' => 4,
                'link' => '/admin/management',
                'name' => 'Bodegas / Salas',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => 8,
                'rgt' => 5,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            4 => 
            array (
                'created_at' => '2023-08-22 20:55:12',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-list',
                'id' => 24,
                'is_external' => 0,
                'lft' => 7,
                'link' => '/app/autorizador/notas',
                'name' => 'CDA',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 41,
                'permission_id' => 7,
                'rgt' => 8,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            5 => 
            array (
                'created_at' => '2023-08-22 20:57:28',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-money-bill-wave-alt',
                'id' => 25,
                'is_external' => 0,
                'lft' => 13,
                'link' => '/app/pagos/pendientes',
                'name' => 'Pagos Pendientes',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 41,
                'permission_id' => 9,
                'rgt' => 14,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            6 => 
            array (
                'created_at' => '2023-08-22 20:59:47',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fab fa-readme',
                'id' => 26,
                'is_external' => 0,
                'lft' => 16,
                'link' => '/admin/management',
                'name' => 'Administración',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 27,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            7 => 
            array (
                'created_at' => '2023-09-05 20:17:54',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-chart-line',
                'id' => 27,
                'is_external' => 0,
                'lft' => 11,
                'link' => '/app/facturador/despacho-pedidos',
                'name' => 'Facturador Despacho',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 41,
                'permission_id' => 10,
                'rgt' => 12,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            8 => 
            array (
                'created_at' => '2023-09-05 20:19:15',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-chart-line',
                'id' => 28,
                'is_external' => 0,
                'lft' => 9,
                'link' => '/app/facturador/retira-aqui',
                'name' => 'Facturador Retiro/Aqui',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 41,
                'permission_id' => 11,
                'rgt' => 10,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            9 => 
            array (
                'created_at' => '2023-09-26 16:44:10',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-calendar-check',
                'id' => 29,
                'is_external' => 0,
                'lft' => 37,
                'link' => '/admin/order-status',
                'name' => 'Estados de la orden',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 5,
                'rgt' => 38,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:59:24',
            ),
            10 => 
            array (
                'created_at' => '2023-09-26 16:45:13',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'far fa-check-circle',
                'id' => 30,
                'is_external' => 0,
                'lft' => 39,
                'link' => '/admin/problem',
                'name' => 'Tipo de rechazo',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 6,
                'rgt' => 40,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:59:35',
            ),
            11 => 
            array (
                'created_at' => '2023-09-26 22:36:04',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-clipboard-check',
                'id' => 32,
                'is_external' => 0,
                'lft' => 31,
                'link' => '/admin/permissions',
                'name' => 'Permisos',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => 13,
                'rgt' => 32,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            12 => 
            array (
                'created_at' => '2023-09-26 22:47:28',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-user-alt',
                'id' => 33,
                'is_external' => 0,
                'lft' => 44,
                'link' => '/admin/user',
                'name' => 'Usuarios',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => 15,
                'rgt' => 45,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            13 => 
            array (
                'created_at' => '2023-09-26 22:49:27',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-user-check',
                'id' => 34,
                'is_external' => 0,
                'lft' => 33,
                'link' => '/admin/role',
                'name' => 'Roles',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => 16,
                'rgt' => 34,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            14 => 
            array (
                'created_at' => '2023-09-27 16:40:01',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-user-friends',
                'id' => 35,
                'is_external' => 0,
                'lft' => 17,
                'link' => '/admin/customer',
                'name' => 'Clientes',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 17,
                'rgt' => 18,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            15 => 
            array (
                'created_at' => '2023-10-17 13:37:58',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-warehouse',
                'id' => 36,
                'is_external' => 0,
                'lft' => 19,
                'link' => '/admin/warehouse',
                'name' => 'Bodega',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 18,
                'rgt' => 20,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            16 => 
            array (
                'created_at' => '2023-10-24 02:14:19',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-cog',
                'id' => 37,
                'is_external' => 0,
                'lft' => 41,
                'link' => '/admin/setting/create',
                'name' => 'Ajustes Generales',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => 19,
                'rgt' => 42,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            17 => 
            array (
                'created_at' => '2023-11-14 14:25:44',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-book',
                'id' => 38,
                'is_external' => 0,
                'lft' => 25,
                'link' => '/admin/log-order',
                'name' => 'Historial de ordenes',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 20,
                'rgt' => 26,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            18 => 
            array (
                'created_at' => '2023-11-14 15:22:00',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-box-open',
                'id' => 39,
                'is_external' => 0,
                'lft' => 21,
                'link' => '/admin/product',
                'name' => 'Productos',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 21,
                'rgt' => 22,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            19 => 
            array (
                'created_at' => '2023-11-14 15:54:51',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-user-friends',
                'id' => 40,
                'is_external' => 0,
                'lft' => 23,
                'link' => '/admin/sales-person',
                'name' => 'Vendedores',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 22,
                'rgt' => 24,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:44:02',
            ),
            20 => 
            array (
                'created_at' => '2023-11-14 16:55:01',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-check-double',
                'id' => 41,
                'is_external' => 0,
                'lft' => 6,
                'link' => '#',
                'name' => 'Gestión',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 15,
                'type' => NULL,
                'updated_at' => '2023-11-15 19:12:17',
            ),
            21 => 
            array (
                'created_at' => '2023-11-15 18:43:40',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-shipping-fast',
                'id' => 42,
                'is_external' => 0,
                'lft' => 35,
                'link' => '/admin/method-shipping',
                'name' => 'Método de envíos',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 23,
                'rgt' => 36,
                'type' => NULL,
                'updated_at' => '2023-11-15 18:59:06',
            ),
        ));
        
        
    }
}