<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'created_at' => '2023-08-04 20:19:55',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-list',
                'id' => 1,
                'is_external' => 0,
                'lft' => 19,
                'link' => '/admin/menu-item',
                'name' => 'Menu',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => NULL,
                'rgt' => 20,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            1 => 
            array (
                'created_at' => '2023-08-21 19:40:35',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-cog',
                'id' => 6,
                'is_external' => 0,
                'lft' => 18,
                'link' => NULL,
                'name' => 'Configuraciones',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 29,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            2 => 
            array (
                'created_at' => '2023-08-21 20:27:03',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-home',
                'id' => 22,
                'is_external' => 0,
                'lft' => 2,
                'link' => '/admin/dashboard',
                'name' => 'Panel',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 3,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            3 => 
            array (
                'created_at' => '2023-08-21 20:34:28',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-warehouse',
                'id' => 23,
                'is_external' => 0,
                'lft' => 4,
                'link' => '/admin/management',
                'name' => 'Bodegas / Salas',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 5,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            4 => 
            array (
                'created_at' => '2023-08-22 20:55:12',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-list',
                'id' => 24,
                'is_external' => 1,
                'lft' => 7,
                'link' => '/app/autorizador/notas',
                'name' => 'CDA',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 7,
                'rgt' => 8,
                'type' => NULL,
                'updated_at' => '2023-10-13 12:10:57',
            ),
            5 => 
            array (
                'created_at' => '2023-08-22 20:57:28',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-money-bill-wave-alt',
                'id' => 25,
                'is_external' => 1,
                'lft' => 9,
                'link' => '/app/pagos/pendientes',
                'name' => 'Pagos Pendientes',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 9,
                'rgt' => 10,
                'type' => NULL,
                'updated_at' => '2023-10-13 12:10:18',
            ),
            6 => 
            array (
                'created_at' => '2023-08-22 20:59:47',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fab fa-readme',
                'id' => 26,
                'is_external' => 0,
                'lft' => 6,
                'link' => '/admin/management',
                'name' => 'Administración',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 17,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            7 => 
            array (
                'created_at' => '2023-09-05 20:17:54',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-chart-line',
                'id' => 27,
                'is_external' => 1,
                'lft' => 11,
                'link' => '/app/facturador/despacho-pedidos',
                'name' => 'Facturador Despacho',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => 10,
                'rgt' => 12,
                'type' => NULL,
                'updated_at' => '2023-10-13 12:09:52',
            ),
            8 => 
            array (
                'created_at' => '2023-09-05 20:19:15',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-chart-line',
                'id' => 28,
                'is_external' => 1,
                'lft' => 13,
                'link' => NULL,
                'name' => 'Facturador Retiro/Aqui',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => NULL,
                'rgt' => 14,
                'type' => NULL,
                'updated_at' => '2023-10-13 12:10:35',
            ),
            9 => 
            array (
                'created_at' => '2023-09-26 16:44:10',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-calendar-check',
                'id' => 29,
                'is_external' => 0,
                'lft' => 25,
                'link' => '/admin/order-status',
                'name' => 'Estados de la orden',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => NULL,
                'rgt' => 26,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            10 => 
            array (
                'created_at' => '2023-09-26 16:45:13',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'far fa-check-circle',
                'id' => 30,
                'is_external' => 0,
                'lft' => 27,
                'link' => '/admin/problem',
                'name' => 'Tipo de rechazo',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => 6,
                'rgt' => 28,
                'type' => NULL,
                'updated_at' => '2023-10-13 12:08:11',
            ),
            11 => 
            array (
                'created_at' => '2023-09-26 22:36:04',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-clipboard-check',
                'id' => 32,
                'is_external' => 0,
                'lft' => 21,
                'link' => '/admin/permissions',
                'name' => 'Permisos',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => NULL,
                'rgt' => 22,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            12 => 
            array (
                'created_at' => '2023-09-26 22:47:28',
                'deleted_at' => NULL,
                'depth' => 1,
                'icon' => 'fas fa-user-alt',
                'id' => 33,
                'is_external' => 0,
                'lft' => 30,
                'link' => '/admin/user',
                'name' => 'Usuarios',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => NULL,
                'permission_id' => NULL,
                'rgt' => 31,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            13 => 
            array (
                'created_at' => '2023-09-26 22:49:27',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-user-check',
                'id' => 34,
                'is_external' => 0,
                'lft' => 23,
                'link' => '/admin/role',
                'name' => 'Roles',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 6,
                'permission_id' => NULL,
                'rgt' => 24,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
            14 => 
            array (
                'created_at' => '2023-09-27 16:40:01',
                'deleted_at' => NULL,
                'depth' => 2,
                'icon' => 'fas fa-user-friends',
                'id' => 35,
                'is_external' => 0,
                'lft' => 15,
                'link' => '/admin/customer',
                'name' => 'Clientes',
                'order' => 0,
                'page_id' => NULL,
                'parent_id' => 26,
                'permission_id' => NULL,
                'rgt' => 16,
                'type' => NULL,
                'updated_at' => '2023-09-27 16:42:44',
            ),
        ));
        
        
    }
}