<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SalesPersonsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sales_persons')->delete();
        
        \DB::table('sales_persons')->insert(array (
            0 => 
            array (
                'id' => 1,
                'SalesEmployeeCode' => -1,
                'SalesEmployeeName' => '-Ningún empleado del departamento de ventas-',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tYES',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            1 => 
            array (
                'id' => 2,
                'SalesEmployeeCode' => 2,
                'SalesEmployeeName' => 'Eduardo Acevedo',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            2 => 
            array (
                'id' => 3,
                'SalesEmployeeCode' => 3,
                'SalesEmployeeName' => 'Carlos Veliz',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            3 => 
            array (
                'id' => 4,
                'SalesEmployeeCode' => 4,
                'SalesEmployeeName' => 'Franco Parraguez',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            4 => 
            array (
                'id' => 5,
                'SalesEmployeeCode' => 5,
                'SalesEmployeeName' => 'Vanessa Montilla',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            5 => 
            array (
                'id' => 6,
                'SalesEmployeeCode' => 6,
                'SalesEmployeeName' => 'Yohan Maloni',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            6 => 
            array (
                'id' => 7,
                'SalesEmployeeCode' => 27,
                'SalesEmployeeName' => 'Juan Perez',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            7 => 
            array (
                'id' => 8,
                'SalesEmployeeCode' => 12,
                'SalesEmployeeName' => 'FUENTES CID CAMILA FRANCISCA',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            8 => 
            array (
                'id' => 9,
                'SalesEmployeeCode' => 8,
                'SalesEmployeeName' => 'Administracion',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            9 => 
            array (
                'id' => 10,
                'SalesEmployeeCode' => 9,
                'SalesEmployeeName' => 'Virtual',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            10 => 
            array (
                'id' => 11,
                'SalesEmployeeCode' => 13,
                'SalesEmployeeName' => 'Fuentes Alvarado Marcelino Roberto',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            11 => 
            array (
                'id' => 12,
                'SalesEmployeeCode' => 11,
                'SalesEmployeeName' => 'Escobar Castillo Yuleiny Karelis',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            12 => 
            array (
                'id' => 13,
                'SalesEmployeeCode' => 14,
                'SalesEmployeeName' => 'Bernales Cisternas Luis Enrique',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            13 => 
            array (
                'id' => 14,
                'SalesEmployeeCode' => 15,
                'SalesEmployeeName' => 'Bobadilla Cevo Javier Antonio',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            14 => 
            array (
                'id' => 15,
                'SalesEmployeeCode' => 16,
                'SalesEmployeeName' => 'Briceño Barrios Tahis Yanira',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            15 => 
            array (
                'id' => 16,
                'SalesEmployeeCode' => 17,
                'SalesEmployeeName' => 'FUENTES CID GONZALO RODRIGO',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            16 => 
            array (
                'id' => 17,
                'SalesEmployeeCode' => 18,
                'SalesEmployeeName' => 'Montilla Leira Yohana Venessa',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            17 => 
            array (
                'id' => 18,
                'SalesEmployeeCode' => 19,
                'SalesEmployeeName' => 'LEIVA ESCOBEDO ENZO JAVIER',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            18 => 
            array (
                'id' => 19,
                'SalesEmployeeCode' => 20,
                'SalesEmployeeName' => 'Maloni Mocco Yohan Moisés',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            19 => 
            array (
                'id' => 20,
                'SalesEmployeeCode' => 21,
                'SalesEmployeeName' => 'Chacon Chacon Francisco Javier',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            20 => 
            array (
                'id' => 21,
                'SalesEmployeeCode' => 22,
                'SalesEmployeeName' => 'Parraguez Nuñez Franco Alexander',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            21 => 
            array (
                'id' => 22,
                'SalesEmployeeCode' => 23,
                'SalesEmployeeName' => 'Acevedo Donoso Eduardo del Carmen',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            22 => 
            array (
                'id' => 23,
                'SalesEmployeeCode' => 24,
                'SalesEmployeeName' => 'LOPES PESTANA NATALIA',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            23 => 
            array (
                'id' => 24,
                'SalesEmployeeCode' => 25,
                'SalesEmployeeName' => 'VELIZ FARIA CARLOS EDUARDO',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            24 => 
            array (
                'id' => 25,
                'SalesEmployeeCode' => 26,
                'SalesEmployeeName' => 'Salinas Uribe Yocelin Alicia',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            25 => 
            array (
                'id' => 26,
                'SalesEmployeeCode' => 28,
                'SalesEmployeeName' => 'Javier Bobadilla',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            26 => 
            array (
                'id' => 27,
                'SalesEmployeeCode' => 31,
                'SalesEmployeeName' => 'Luis Bernales',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            27 => 
            array (
                'id' => 28,
                'SalesEmployeeCode' => 29,
                'SalesEmployeeName' => 'Ender Moron',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            28 => 
            array (
                'id' => 29,
                'SalesEmployeeCode' => 30,
                'SalesEmployeeName' => 'Consuelo Fuentes',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            29 => 
            array (
                'id' => 30,
                'SalesEmployeeCode' => 1,
                'SalesEmployeeName' => 'Enzo Leiva',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 0,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            30 => 
            array (
                'id' => 31,
                'SalesEmployeeCode' => 32,
                'SalesEmployeeName' => 'Ruth Machuca',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            31 => 
            array (
                'id' => 32,
                'SalesEmployeeCode' => 33,
                'SalesEmployeeName' => 'Benjamin Toledo Chacon',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            32 => 
            array (
                'id' => 33,
                'SalesEmployeeCode' => 34,
                'SalesEmployeeName' => 'Sofia Lagos Cartes',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
            33 => 
            array (
                'id' => 34,
                'SalesEmployeeCode' => 35,
                'SalesEmployeeName' => 'Lia Fuentes Cid',
                'CommissionForSalesEmployee' => 0.0,
                'CommissionGroup' => 0.0,
                'Locked' => 'tNO',
                'EmployeeID' => NULL,
                'Active' => 1,
                'Telephone' => NULL,
                'Mobile' => NULL,
                'Email' => NULL,
                'created_at' => '2023-11-08 01:47:46',
                'updated_at' => '2023-11-08 01:47:46',
            ),
        ));
        
        
    }
}