<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'hash' => '6d4d63dfb23efeae5d0245d750a39766',
                'code' => 1,
                'name' => 'Administrador del sistema',
                'email' => 'super@dutech.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bPxgTM0pc1F5tsEZdgcQ6elOIVIc2Xm1eBrGk4N5th/9ED3XngwU6',
                'remember_token' => NULL,
                'created_at' => '2023-07-10 17:29:44',
                'updated_at' => '2023-10-17 14:01:21',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'hash' => 'b9122f34544744fd3d2c84284e8c83f9',
                'code' => 2,
                'name' => 'Armando Torres',
                'email' => 'cda@dutech.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CN4IsvWlNPpa/FrzB4COEOnhXEhm/R65BgFwK/iEc.a1TFGZKdDhm',
                'remember_token' => NULL,
                'created_at' => '2023-09-26 17:16:18',
                'updated_at' => '2023-09-26 17:21:33',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'hash' => '7e64d0de5d0681f4327ee48f104f725f',
                'code' => 3,
                'name' => 'Miguel Cabrera',
                'email' => 'picker@dutech.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$XUEFUg3Ogaob/Ile2dpF7.IpoBOBsdgwFyrdr6gz.Y7E/cq.AfRS6',
                'remember_token' => NULL,
                'created_at' => '2023-09-26 17:17:50',
                'updated_at' => '2023-09-26 17:20:28',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'hash' => '4226b51ad645788acf5cc54427dbc7c8',
                'code' => 4,
                'name' => 'Juan toro',
                'email' => 'revisor@dutech.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$H8wzWP4HzW0YGkkTX/iUEuYFbtY2gHxGPlobiDm9fNVXN17z8/xXG',
                'remember_token' => NULL,
                'created_at' => '2023-09-26 17:18:40',
                'updated_at' => '2023-09-26 17:19:59',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'hash' => 'ee570938f30b796ceca8a5e90e05895a',
                'code' => 5,
                'name' => 'Pedro Perez',
                'email' => 'administracion@dutech.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$L/qQVSZwFy7vsygXS/eOj.85WNLOuryzAW3R4xI4qJfOoKzQ0.f/K',
                'remember_token' => NULL,
                'created_at' => '2023-09-26 17:19:18',
                'updated_at' => '2023-09-26 17:19:18',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'hash' => '050cd70238d5b3c77b6dfe4f4fd30232',
                'code' => 6,
                'name' => 'Javier Bobadilla',
                'email' => 'javier@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CwNggph27JV59ODbEstkl.U570uSt57e6NedZUOBnvghAFHFRGaju',
                'remember_token' => NULL,
                'created_at' => '2023-11-20 20:50:10',
                'updated_at' => '2023-11-20 20:50:10',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => '956448149',
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'hash' => 'dcc0e2b29ffc15b84ac08e47b883e47d',
                'code' => 7,
                'name' => 'Yocelin Salinas',
                'email' => 'ysalinas@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zEvbLaJq3RFcePVQLn8/xeLd.OHnucZk0RtxcuMCsjNHYD0xL8/4e',
                'remember_token' => NULL,
                'created_at' => '2023-11-23 17:46:36',
                'updated_at' => '2023-11-23 17:46:36',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => '+56975216056',
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'hash' => '4aea332e85d693d6f9400c44a312a700',
                'code' => 8,
                'name' => 'Sofia Lagos',
                'email' => 'pagos@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jgG7hR3mUzwq2GY/Qil91ud5gLEyjnZPjZNrYc33w5tzC8Z2HlIq2',
                'remember_token' => NULL,
                'created_at' => '2023-11-23 17:47:52',
                'updated_at' => '2023-11-23 17:47:52',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => '+56952360210',
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'hash' => '1d89c02818c756d286853f895a4f8559',
                'code' => 9,
                'name' => 'Alessandra Guercio',
                'email' => 'cda@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$F41OlvBLPOyl8rdPTweROeItcu5629DjvLHkzK317quCM5gX54rlm',
                'remember_token' => NULL,
                'created_at' => '2023-11-24 12:06:58',
                'updated_at' => '2023-11-24 12:06:58',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'hash' => '11450b830c27b7ec8acc43037dbd583c',
                'code' => 10,
                'name' => 'Cristián Córdova',
                'email' => 'bodegavictoria@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pGDeDK08YdtMUCxcMZN2l.xvmobz2QgiGC4SXrnrmUdUwRjhCUNmy',
                'remember_token' => 'JjwbHdjPAg1n2TEUkmFblKb7EtI9ltxs9kaafPEctQmuVdF8hGHlJKnepWss',
                'created_at' => '2023-11-24 12:07:46',
                'updated_at' => '2023-11-24 12:07:46',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'hash' => '7c856d77e165b80c24d143d9986069ef',
                'code' => 11,
                'name' => 'Picker 1 BVM',
                'email' => 'inventarios@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$oxlwUrJ6.d7f6MMTLDTQ8u1wxJu99xyr003VEVWMJKQ3XPcqkFgIm',
                'remember_token' => 'T44KOPMHOptYlQVDbbd9KBvkZoUdw1cYQ2b3BMw6nM9eKcKre7QBODSuS9ep',
                'created_at' => '2023-11-24 12:14:58',
                'updated_at' => '2023-11-24 12:14:58',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'hash' => '3fe28d185b90c7f1ce1a7ffcce429002',
                'code' => 12,
                'name' => 'Gonzalo Fuentes',
                'email' => 'gonzalo@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KMYijJy9EEYus2z2e4kC1ecAv0QPQ4PbR0QQQZfshIqQ.Jm0lQEWa',
                'remember_token' => NULL,
                'created_at' => '2023-11-24 12:53:47',
                'updated_at' => '2023-11-24 12:53:47',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'hash' => 'c7ddba82537ca5668460e85ef7d0518e',
                'code' => 13,
                'name' => 'Francisco Chacón',
                'email' => 'bodegacentral@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cZoDT4DckmguARuqHQB/SefYIIVFjmjaniq1sriDQiCO5waa38yh2',
                'remember_token' => NULL,
                'created_at' => '2023-11-24 13:12:18',
                'updated_at' => '2023-11-24 13:12:18',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'hash' => 'c2bb39a1248512a3c19d5b532134e85f',
                'code' => 14,
                'name' => 'Félix Bastías',
                'email' => 'bse@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$RIAr3VSh7yOTGMnST2OcgO9PumxSjPyPhQXs7xsZ8iNROy/3.Zdym',
                'remember_token' => NULL,
                'created_at' => '2023-11-24 13:16:37',
                'updated_at' => '2023-11-24 13:16:37',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'hash' => '088ca22cc3ced888551fd4d22e268b9d',
                'code' => 15,
                'name' => 'Maloni Mocco Yohan Moisés',
                'email' => 'vendedor1@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$9ZI8PRn3772YBvPAbLV.S.EZLHYQYHMQmqB4sOGIaLVErh7wvo2QC',
                'remember_token' => NULL,
                'created_at' => '2023-12-05 16:44:08',
                'updated_at' => '2023-12-05 16:48:53',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => 19,
            ),
            15 => 
            array (
                'id' => 17,
                'hash' => 'bc1824438e4966bf2373cb6499cac2d5',
                'code' => 16,
                'name' => 'Parraguez Nuñez Franco Alexander',
                'email' => 'vendedor2@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cKULmtjFXnxFA2/Nz/TR.u8UPR4Fp95T.hGj9xGRg9VFCb.qZ0cCu',
                'remember_token' => NULL,
                'created_at' => '2023-12-05 16:44:58',
                'updated_at' => '2023-12-05 16:45:13',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => 21,
            ),
            16 => 
            array (
                'id' => 18,
                'hash' => 'e0b18a537b4ddf56d911292dcb4b9e86',
                'code' => 17,
                'name' => 'Leiva Escobedo Enzo Javier',
                'email' => 'vendedor3@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a7FkHK8JXDW8cfIiJHuzpu7TouhA1aN9FGC6o1WCWvq7pBcNlyzMK',
                'remember_token' => NULL,
                'created_at' => '2023-12-05 16:50:02',
                'updated_at' => '2023-12-05 16:50:36',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => 18,
            ),
            17 => 
            array (
                'id' => 19,
                'hash' => '782323cabbdcdda1d9793915336b61f3',
                'code' => 18,
                'name' => 'Ender Moron',
                'email' => 'vendedor4@tascochile.cl',
                'email_verified_at' => NULL,
                'password' => '$2y$10$AMipxukbmgJzhKXM9qNi5evTXU6NTWEihAktAMmQcC55WRExwY.5q',
                'remember_token' => NULL,
                'created_at' => '2023-12-05 16:51:49',
                'updated_at' => '2023-12-05 16:51:49',
                'internal_key' => NULL,
                'user_code' => NULL,
                'mobile_phone_number' => NULL,
                'defaults' => NULL,
                'branch' => NULL,
                'department' => NULL,
                'sales_person_id' => 28,
            ),
        ));
        
        
    }
}